# Generated by Django 3.2.9 on 2021-12-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20211122_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybar',
            name='code',
            field=models.CharField(db_index=True, max_length=16, null=True, verbose_name='品种代码'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='all_inst',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='品种列表'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='合约代码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='合约代码'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='code',
            field=models.CharField(max_length=16, null=True, verbose_name='当前合约'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='合约代码'),
        ),
    ]
